
package x2x.uv.mx.consumo.wsdl;

import java.math.BigDecimal;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "iPresupuesto", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPresupuesto {


    /**
     * 
     * @return
     *     returns x2x.uv.mx.consumo.wsdl.ArrayOfdecimal
     */
    @WebMethod(action = "http://tempuri.org/iPresupuesto/mostrarPresupuestos")
    @WebResult(name = "mostrarPresupuestosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mostrarPresupuestos", targetNamespace = "http://tempuri.org/", className = "x2x.uv.mx.consumo.wsdl.MostrarPresupuestos")
    @ResponseWrapper(localName = "mostrarPresupuestosResponse", targetNamespace = "http://tempuri.org/", className = "x2x.uv.mx.consumo.wsdl.MostrarPresupuestosResponse")
    @Action(input = "http://tempuri.org/iPresupuesto/mostrarPresupuestos", output = "http://tempuri.org/iPresupuesto/mostrarPresupuestosResponse")
    public ArrayOfdecimal mostrarPresupuestos();

    /**
     * 
     * @param dinero
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/iPresupuesto/agregarPresupuesto")
    @WebResult(name = "agregarPresupuestoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "agregarPresupuesto", targetNamespace = "http://tempuri.org/", className = "x2x.uv.mx.consumo.wsdl.AgregarPresupuesto")
    @ResponseWrapper(localName = "agregarPresupuestoResponse", targetNamespace = "http://tempuri.org/", className = "x2x.uv.mx.consumo.wsdl.AgregarPresupuestoResponse")
    @Action(input = "http://tempuri.org/iPresupuesto/agregarPresupuesto", output = "http://tempuri.org/iPresupuesto/agregarPresupuestoResponse")
    public String agregarPresupuesto(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        int id,
        @WebParam(name = "dinero", targetNamespace = "http://tempuri.org/")
        BigDecimal dinero);

    /**
     * 
     * @param dinero
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/iPresupuesto/quitarPresupuesto")
    @WebResult(name = "quitarPresupuestoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "quitarPresupuesto", targetNamespace = "http://tempuri.org/", className = "x2x.uv.mx.consumo.wsdl.QuitarPresupuesto")
    @ResponseWrapper(localName = "quitarPresupuestoResponse", targetNamespace = "http://tempuri.org/", className = "x2x.uv.mx.consumo.wsdl.QuitarPresupuestoResponse")
    @Action(input = "http://tempuri.org/iPresupuesto/quitarPresupuesto", output = "http://tempuri.org/iPresupuesto/quitarPresupuestoResponse")
    public String quitarPresupuesto(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        int id,
        @WebParam(name = "dinero", targetNamespace = "http://tempuri.org/")
        BigDecimal dinero);

    /**
     * 
     * @param dinero
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://tempuri.org/iPresupuesto/alcancePresupuesto")
    @WebResult(name = "alcancePresupuestoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "alcancePresupuesto", targetNamespace = "http://tempuri.org/", className = "x2x.uv.mx.consumo.wsdl.AlcancePresupuesto")
    @ResponseWrapper(localName = "alcancePresupuestoResponse", targetNamespace = "http://tempuri.org/", className = "x2x.uv.mx.consumo.wsdl.AlcancePresupuestoResponse")
    @Action(input = "http://tempuri.org/iPresupuesto/alcancePresupuesto", output = "http://tempuri.org/iPresupuesto/alcancePresupuestoResponse")
    public boolean alcancePresupuesto(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        int id,
        @WebParam(name = "dinero", targetNamespace = "http://tempuri.org/")
        BigDecimal dinero);

}
