<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://tempuri.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:http="http://schemas.microsoft.com/ws/06/2004/policy/http" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" targetNamespace="http://tempuri.org/" name="iPresupuesto" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/">
      <xs:element name="mostrarPresupuestos">
        <xs:complexType>
          <xs:sequence/>
        </xs:complexType>
      </xs:element>
      <xs:element name="mostrarPresupuestosResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" xmlns:q1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" name="mostrarPresupuestosResult" nillable="true" type="q1:ArrayOfdecimal"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="agregarPresupuesto">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" name="id" type="xs:int"/>
            <xs:element minOccurs="1" name="dinero" type="xs:decimal"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="agregarPresupuestoResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" name="agregarPresupuestoResult" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="quitarPresupuesto">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" name="id" type="xs:int"/>
            <xs:element minOccurs="1" name="dinero" type="xs:decimal"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="quitarPresupuestoResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" name="quitarPresupuestoResult" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="alcancePresupuesto">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" name="id" type="xs:int"/>
            <xs:element minOccurs="1" name="dinero" type="xs:decimal"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="alcancePresupuestoResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" name="alcancePresupuestoResult" type="xs:boolean"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
    <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/">
      <xs:element name="anyType" nillable="true" type="xs:anyType"/>
      <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
      <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
      <xs:element name="boolean" nillable="true" type="xs:boolean"/>
      <xs:element name="byte" nillable="true" type="xs:byte"/>
      <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
      <xs:element name="decimal" nillable="true" type="xs:decimal"/>
      <xs:element name="double" nillable="true" type="xs:double"/>
      <xs:element name="float" nillable="true" type="xs:float"/>
      <xs:element name="int" nillable="true" type="xs:int"/>
      <xs:element name="long" nillable="true" type="xs:long"/>
      <xs:element name="QName" nillable="true" type="xs:QName"/>
      <xs:element name="short" nillable="true" type="xs:short"/>
      <xs:element name="string" nillable="true" type="xs:string"/>
      <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
      <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
      <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
      <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
      <xs:element name="char" nillable="true" type="tns:char"/>
      <xs:simpleType name="char">
        <xs:restriction base="xs:int"/>
      </xs:simpleType>
      <xs:element name="duration" nillable="true" type="tns:duration"/>
      <xs:simpleType name="duration">
        <xs:restriction base="xs:duration">
          <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
          <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
          <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="guid" nillable="true" type="tns:guid"/>
      <xs:simpleType name="guid">
        <xs:restriction base="xs:string">
          <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:attribute name="FactoryType" type="xs:QName"/>
      <xs:attribute name="Id" type="xs:ID"/>
      <xs:attribute name="Ref" type="xs:IDREF"/>
    </xs:schema>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
      <xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/"/>
      <xs:complexType name="ArrayOfdecimal">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="decimal" type="xs:decimal"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfdecimal" nillable="true" type="tns:ArrayOfdecimal"/>
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="iPresupuesto_mostrarPresupuestos_InputMessage">
    <wsdl:part name="parameters" element="tns:mostrarPresupuestos"/>
  </wsdl:message>
  <wsdl:message name="iPresupuesto_mostrarPresupuestos_OutputMessage">
    <wsdl:part name="parameters" element="tns:mostrarPresupuestosResponse"/>
  </wsdl:message>
  <wsdl:message name="iPresupuesto_agregarPresupuesto_InputMessage">
    <wsdl:part name="parameters" element="tns:agregarPresupuesto"/>
  </wsdl:message>
  <wsdl:message name="iPresupuesto_agregarPresupuesto_OutputMessage">
    <wsdl:part name="parameters" element="tns:agregarPresupuestoResponse"/>
  </wsdl:message>
  <wsdl:message name="iPresupuesto_quitarPresupuesto_InputMessage">
    <wsdl:part name="parameters" element="tns:quitarPresupuesto"/>
  </wsdl:message>
  <wsdl:message name="iPresupuesto_quitarPresupuesto_OutputMessage">
    <wsdl:part name="parameters" element="tns:quitarPresupuestoResponse"/>
  </wsdl:message>
  <wsdl:message name="iPresupuesto_alcancePresupuesto_InputMessage">
    <wsdl:part name="parameters" element="tns:alcancePresupuesto"/>
  </wsdl:message>
  <wsdl:message name="iPresupuesto_alcancePresupuesto_OutputMessage">
    <wsdl:part name="parameters" element="tns:alcancePresupuestoResponse"/>
  </wsdl:message>
  <wsdl:portType name="iPresupuesto">
    <wsdl:operation name="mostrarPresupuestos">
      <wsdl:input wsam:Action="http://tempuri.org/iPresupuesto/mostrarPresupuestos" message="tns:iPresupuesto_mostrarPresupuestos_InputMessage"/>
      <wsdl:output wsam:Action="http://tempuri.org/iPresupuesto/mostrarPresupuestosResponse" message="tns:iPresupuesto_mostrarPresupuestos_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="agregarPresupuesto">
      <wsdl:input wsam:Action="http://tempuri.org/iPresupuesto/agregarPresupuesto" message="tns:iPresupuesto_agregarPresupuesto_InputMessage"/>
      <wsdl:output wsam:Action="http://tempuri.org/iPresupuesto/agregarPresupuestoResponse" message="tns:iPresupuesto_agregarPresupuesto_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="quitarPresupuesto">
      <wsdl:input wsam:Action="http://tempuri.org/iPresupuesto/quitarPresupuesto" message="tns:iPresupuesto_quitarPresupuesto_InputMessage"/>
      <wsdl:output wsam:Action="http://tempuri.org/iPresupuesto/quitarPresupuestoResponse" message="tns:iPresupuesto_quitarPresupuesto_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="alcancePresupuesto">
      <wsdl:input wsam:Action="http://tempuri.org/iPresupuesto/alcancePresupuesto" message="tns:iPresupuesto_alcancePresupuesto_InputMessage"/>
      <wsdl:output wsam:Action="http://tempuri.org/iPresupuesto/alcancePresupuestoResponse" message="tns:iPresupuesto_alcancePresupuesto_OutputMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_iPresupuesto" type="tns:iPresupuesto">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="mostrarPresupuestos">
      <soap:operation soapAction="http://tempuri.org/iPresupuesto/mostrarPresupuestos" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="agregarPresupuesto">
      <soap:operation soapAction="http://tempuri.org/iPresupuesto/agregarPresupuesto" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="quitarPresupuesto">
      <soap:operation soapAction="http://tempuri.org/iPresupuesto/quitarPresupuesto" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="alcancePresupuesto">
      <soap:operation soapAction="http://tempuri.org/iPresupuesto/alcancePresupuesto" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="iPresupuesto">
    <wsdl:port name="BasicHttpBinding_iPresupuesto" binding="tns:BasicHttpBinding_iPresupuesto">
      <soap:address location="http://nuevoproyecto-production.up.railway.app/Presupuesto.equipo3"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>