
package xx.uv.mx.consumo.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "comprasPort", targetNamespace = "https://t4is.uv.mx/compras")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ComprasPort {


    /**
     * 
     * @param crearPresupuestoRequest
     * @return
     *     returns xx.uv.mx.consumo.wsdl.CrearPresupuestoResponse
     */
    @WebMethod(operationName = "CrearPresupuesto")
    @WebResult(name = "CrearPresupuestoResponse", targetNamespace = "t4is.uv.mx/compras", partName = "CrearPresupuestoResponse")
    public CrearPresupuestoResponse crearPresupuesto(
        @WebParam(name = "CrearPresupuestoRequest", targetNamespace = "t4is.uv.mx/compras", partName = "CrearPresupuestoRequest")
        CrearPresupuestoRequest crearPresupuestoRequest);

    /**
     * 
     * @param crearFacturaRequest
     * @return
     *     returns xx.uv.mx.consumo.wsdl.CrearFacturaResponse
     */
    @WebMethod(operationName = "CrearFactura")
    @WebResult(name = "CrearFacturaResponse", targetNamespace = "t4is.uv.mx/compras", partName = "CrearFacturaResponse")
    public CrearFacturaResponse crearFactura(
        @WebParam(name = "CrearFacturaRequest", targetNamespace = "t4is.uv.mx/compras", partName = "CrearFacturaRequest")
        CrearFacturaRequest crearFacturaRequest);

    /**
     * 
     * @param consultarFacturaRequest
     * @return
     *     returns xx.uv.mx.consumo.wsdl.ConsultarFacturaResponse
     */
    @WebMethod(operationName = "ConsultarFactura")
    @WebResult(name = "ConsultarFacturaResponse", targetNamespace = "t4is.uv.mx/compras", partName = "ConsultarFacturaResponse")
    public ConsultarFacturaResponse consultarFactura(
        @WebParam(name = "ConsultarFacturaRequest", targetNamespace = "t4is.uv.mx/compras", partName = "ConsultarFacturaRequest")
        ConsultarFacturaRequest consultarFacturaRequest);

    /**
     * 
     * @param registrarCompraRequest
     * @return
     *     returns xx.uv.mx.consumo.wsdl.RegistrarCompraResponse
     */
    @WebMethod(operationName = "RegistrarCompra")
    @WebResult(name = "RegistrarCompraResponse", targetNamespace = "t4is.uv.mx/compras", partName = "RegistrarCompraResponse")
    public RegistrarCompraResponse registrarCompra(
        @WebParam(name = "RegistrarCompraRequest", targetNamespace = "t4is.uv.mx/compras", partName = "RegistrarCompraRequest")
        RegistrarCompraRequest registrarCompraRequest);

    /**
     * 
     * @param actualizarFacturaRequest
     * @return
     *     returns xx.uv.mx.consumo.wsdl.ActualizarFacturaResponse
     */
    @WebMethod(operationName = "ActualizarFactura")
    @WebResult(name = "ActualizarFacturaResponse", targetNamespace = "t4is.uv.mx/compras", partName = "ActualizarFacturaResponse")
    public ActualizarFacturaResponse actualizarFactura(
        @WebParam(name = "ActualizarFacturaRequest", targetNamespace = "t4is.uv.mx/compras", partName = "ActualizarFacturaRequest")
        ActualizarFacturaRequest actualizarFacturaRequest);

    /**
     * 
     * @param consultarPresupuestoRequest
     * @return
     *     returns xx.uv.mx.consumo.wsdl.ConsultarPresupuestoResponse
     */
    @WebMethod(operationName = "ConsultarPresupuesto")
    @WebResult(name = "ConsultarPresupuestoResponse", targetNamespace = "t4is.uv.mx/compras", partName = "ConsultarPresupuestoResponse")
    public ConsultarPresupuestoResponse consultarPresupuesto(
        @WebParam(name = "ConsultarPresupuestoRequest", targetNamespace = "t4is.uv.mx/compras", partName = "ConsultarPresupuestoRequest")
        ConsultarPresupuestoRequest consultarPresupuestoRequest);

    /**
     * 
     * @param actualizarPresupuestoRequest
     * @return
     *     returns xx.uv.mx.consumo.wsdl.ActualizarPresupuestoResponse
     */
    @WebMethod(operationName = "ActualizarPresupuesto")
    @WebResult(name = "ActualizarPresupuestoResponse", targetNamespace = "t4is.uv.mx/compras", partName = "ActualizarPresupuestoResponse")
    public ActualizarPresupuestoResponse actualizarPresupuesto(
        @WebParam(name = "ActualizarPresupuestoRequest", targetNamespace = "t4is.uv.mx/compras", partName = "ActualizarPresupuestoRequest")
        ActualizarPresupuestoRequest actualizarPresupuestoRequest);

}
