
package x3x.uv.mx.consumo.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "iProductos", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/C:/Users/Carlo/Desktop/clienteGeneral/src/main/resources/Productos.wsdl")
public class IProductos_Service
    extends Service
{

    private final static URL IPRODUCTOS_WSDL_LOCATION;
    private final static WebServiceException IPRODUCTOS_EXCEPTION;
    private final static QName IPRODUCTOS_QNAME = new QName("http://tempuri.org/", "iProductos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Carlo/Desktop/clienteGeneral/src/main/resources/Productos.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IPRODUCTOS_WSDL_LOCATION = url;
        IPRODUCTOS_EXCEPTION = e;
    }

    public IProductos_Service() {
        super(__getWsdlLocation(), IPRODUCTOS_QNAME);
    }

    public IProductos_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), IPRODUCTOS_QNAME, features);
    }

    public IProductos_Service(URL wsdlLocation) {
        super(wsdlLocation, IPRODUCTOS_QNAME);
    }

    public IProductos_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IPRODUCTOS_QNAME, features);
    }

    public IProductos_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IProductos_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IProductos
     */
    @WebEndpoint(name = "BasicHttpBinding_iProductos")
    public IProductos getBasicHttpBindingIProductos() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_iProductos"), IProductos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IProductos
     */
    @WebEndpoint(name = "BasicHttpBinding_iProductos")
    public IProductos getBasicHttpBindingIProductos(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_iProductos"), IProductos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IPRODUCTOS_EXCEPTION!= null) {
            throw IPRODUCTOS_EXCEPTION;
        }
        return IPRODUCTOS_WSDL_LOCATION;
    }

}
