
package xx.uv.mx.consumo.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "IFacturaService", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/C:/Users/Carlo/Downloads/clienteGeneral/src/main/resources/Facturas.wsdl")
public class IFacturaService_Service
    extends Service
{

    private final static URL IFACTURASERVICE_WSDL_LOCATION;
    private final static WebServiceException IFACTURASERVICE_EXCEPTION;
    private final static QName IFACTURASERVICE_QNAME = new QName("http://tempuri.org/", "IFacturaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Carlo/Downloads/clienteGeneral/src/main/resources/Facturas.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IFACTURASERVICE_WSDL_LOCATION = url;
        IFACTURASERVICE_EXCEPTION = e;
    }

    public IFacturaService_Service() {
        super(__getWsdlLocation(), IFACTURASERVICE_QNAME);
    }

    public IFacturaService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), IFACTURASERVICE_QNAME, features);
    }

    public IFacturaService_Service(URL wsdlLocation) {
        super(wsdlLocation, IFACTURASERVICE_QNAME);
    }

    public IFacturaService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IFACTURASERVICE_QNAME, features);
    }

    public IFacturaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IFacturaService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IFacturaService
     */
    @WebEndpoint(name = "BasicHttpBinding_IFacturaService_soap")
    public IFacturaService getBasicHttpBindingIFacturaServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IFacturaService_soap"), IFacturaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFacturaService
     */
    @WebEndpoint(name = "BasicHttpBinding_IFacturaService_soap")
    public IFacturaService getBasicHttpBindingIFacturaServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IFacturaService_soap"), IFacturaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IFACTURASERVICE_EXCEPTION!= null) {
            throw IFACTURASERVICE_EXCEPTION;
        }
        return IFACTURASERVICE_WSDL_LOCATION;
    }

}
