
package xx.uv.mx.consumo.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IFacturaService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IFacturaService {


    /**
     * 
     * @return
     *     returns xx.uv.mx.consumo.wsdl.ArrayOfFactura
     */
    @WebMethod(operationName = "GetAllFacturas", action = "http://tempuri.org/IFacturaService/GetAllFacturas")
    @WebResult(name = "GetAllFacturasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllFacturas", targetNamespace = "http://tempuri.org/", className = "xx.uv.mx.consumo.wsdl.GetAllFacturas")
    @ResponseWrapper(localName = "GetAllFacturasResponse", targetNamespace = "http://tempuri.org/", className = "xx.uv.mx.consumo.wsdl.GetAllFacturasResponse")
    public ArrayOfFactura getAllFacturas();

    /**
     * 
     * @param id
     * @return
     *     returns xx.uv.mx.consumo.wsdl.Factura
     */
    @WebMethod(operationName = "GetFacturaById", action = "http://tempuri.org/IFacturaService/GetFacturaById")
    @WebResult(name = "GetFacturaByIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFacturaById", targetNamespace = "http://tempuri.org/", className = "xx.uv.mx.consumo.wsdl.GetFacturaById")
    @ResponseWrapper(localName = "GetFacturaByIdResponse", targetNamespace = "http://tempuri.org/", className = "xx.uv.mx.consumo.wsdl.GetFacturaByIdResponse")
    public Factura getFacturaById(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        int id);

    /**
     * 
     * @param factura
     * @return
     *     returns xx.uv.mx.consumo.wsdl.Factura
     */
    @WebMethod(operationName = "CreateFactura", action = "http://tempuri.org/IFacturaService/CreateFactura")
    @WebResult(name = "CreateFacturaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateFactura", targetNamespace = "http://tempuri.org/", className = "xx.uv.mx.consumo.wsdl.CreateFactura")
    @ResponseWrapper(localName = "CreateFacturaResponse", targetNamespace = "http://tempuri.org/", className = "xx.uv.mx.consumo.wsdl.CreateFacturaResponse")
    public Factura createFactura(
        @WebParam(name = "factura", targetNamespace = "http://tempuri.org/")
        Factura factura);

    /**
     * 
     * @param factura
     * @return
     *     returns xx.uv.mx.consumo.wsdl.Factura
     */
    @WebMethod(operationName = "UpdateFactura", action = "http://tempuri.org/IFacturaService/UpdateFactura")
    @WebResult(name = "UpdateFacturaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateFactura", targetNamespace = "http://tempuri.org/", className = "xx.uv.mx.consumo.wsdl.UpdateFactura")
    @ResponseWrapper(localName = "UpdateFacturaResponse", targetNamespace = "http://tempuri.org/", className = "xx.uv.mx.consumo.wsdl.UpdateFacturaResponse")
    public Factura updateFactura(
        @WebParam(name = "factura", targetNamespace = "http://tempuri.org/")
        Factura factura);

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "DeleteFactura", action = "http://tempuri.org/IFacturaService/DeleteFactura")
    @WebResult(name = "DeleteFacturaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteFactura", targetNamespace = "http://tempuri.org/", className = "xx.uv.mx.consumo.wsdl.DeleteFactura")
    @ResponseWrapper(localName = "DeleteFacturaResponse", targetNamespace = "http://tempuri.org/", className = "xx.uv.mx.consumo.wsdl.DeleteFacturaResponse")
    public boolean deleteFactura(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        int id);

}
